[workspace]
resolver = "2"
members = [
    "ctos",
    "web",
]

[workspace.package]
version = "0.2.7"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.68.0"

[profile.release]
panic = 'abort'
lto = true
opt-level = 3


[profile.dev]
debug = 1
